adding visual test and automation framework modifications
abstracta/SeleniumAutomationFW pull request #1
Opened 2017-04-10 19:35 UTC by ocalderinp

2017-04-15 18:22 UTC, alexisalvarez88 commented on src/main/java/automation_framework/handlers/PageObjectsHandler.java
> +package automation_framework.handlers;
Utilizar camelCase 'automationFramework'

2017-04-15 18:23 UTC, alexisalvarez88 commented on src/main/java/automation_framework/handlers/PageObjectsHandler.java
> +    protected PageObjectsHandler(WebDriver _driver, Eyes _eyes){
No usar _ mejor utilizar el keyword "this" ejemplo:  this.driver = driver;

2017-04-15 18:23 UTC, alexisalvarez88 commented on src/main/java/automation_framework/page_objects/BaseElement.java
> +        BaseElement.driver = _driver;
utilizar "this"

2017-04-15 18:24 UTC, alexisalvarez88 commented on src/main/java/automation_framework/page_objects/BaseElement.java
> +    public void addWait(Wait _wait){
como utilizamos camel case "_" innecesario

2017-04-15 18:25 UTC, alexisalvarez88 commented on src/main/java/automation_framework/page_objects/BaseElement.java
> +    public void clear(WebElement _element){
Lo mismo "_" innecesario

2017-04-15 18:25 UTC, alexisalvarez88 commented on src/main/java/automation_framework/page_objects/BaseElement.java
> +
Quitar espacio en blanco

2017-04-15 18:27 UTC, alexisalvarez88 commented on src/main/java/automation_framework/page_objects/BasePage.java
> +    public void addWait(Wait _wait){
BaseElement y BasePage tienen el mismo metodo duplicado addWait. Debemos poner esto en un lugar en común.

2017-04-15 18:29 UTC, alexisalvarez88 commented on src/main/java/automation_framework/tests/BaseTest.java
> +    private static String BROWSER = properties.getString("BROWSER").toUpperCase();;
Utilizar camelCase, "browser", solo para constantes esta bien utilizar todo mayusculas

2017-04-15 18:30 UTC, alexisalvarez88 commented on src/main/java/automation_framework/tests/BaseTest.java
> +        String batch_name = (!System.getenv("JOB_NAME").isEmpty())? System.getenv("JOB_NAME") : "Local";
camelCase

2017-04-15 18:31 UTC, alexisalvarez88 commented on src/main/java/automation_framework/tests/BaseTest.java
> +                baseline += " Firefox";
Podriamos crear un enumerador para Todos los browsers

2017-04-15 18:33 UTC, alexisalvarez88 commented on src/main/java/automation_framework/utils/WebDriverUtils.java
> +	public static void waitTime(WebDriver _driver, int _time){
Nuevamente no utilizar "_"

2017-04-15 18:33 UTC, alexisalvarez88 commented on src/main/java/us/abstracta/opencart/bases/OpencartBaseElement.java
> +
espacio en blanco

2017-04-15 18:34 UTC, alexisalvarez88 commented on src/main/java/us/abstracta/opencart/page_objects_handler/OpencartPageObjectsHandler.java
> +
espacio en blanco

2017-04-15 18:35 UTC, alexisalvarez88 commented on src/main/java/us/abstracta/opencart/pages/Cart.java
> +
espacios en blanco

2017-04-15 18:37 UTC, alexisalvarez88 commented on src/main/java/us/abstracta/opencart/pages/HomePage.java
> +
Espacio en blanco

2017-04-15 18:38 UTC, alexisalvarez88 commented on src/main/java/us/abstracta/opencart/pages/SearchResultPage.java
> +
Espacio en blanco

2017-04-15 18:41 UTC, alexisalvarez88 requested changes
Excelentes cambios Oscar, pero antes veamos los comentarios que agregue. Sientete libre de contactarme y los trabajamos juntos.

2017-04-18 13:17 UTC, ocalderinp commented on src/main/java/automation_framework/page_objects/BasePage.java
> +    public void addWait(Wait _wait){
movido a WebDriverUtils

2017-04-18 13:40 UTC, merged